First task
1lyan/nodejs_app pull request #1
Opened 2021-10-25 09:47 UTC by 1lyan

This is the first task in the nodejs course

2021-10-25 21:08 UTC, rfist requested changes
Probably content-type `application/json` is too much for one short string, but we can live with it. 
Fix please other comments

2021-10-25 21:08 UTC, rfist commented on config.js
> +  ENV: process.env.ENV,
env must be passed as a cli argument, so command `node app.js testenv` will give you output `env is testenv`
what are you looking for is `process.argv`

2021-10-25 21:08 UTC, rfist commented on app.js
> +}).listen(config.APP_PORT, () => console.log(message));
Please, create `logger.js` and import logging functions from it.

2021-10-26 17:11 UTC, rfist approved these changes
Nice work!

2021-10-26 18:27 UTC, 1lyan commented
> Nice work!

@rfist , thanks :)

2021-10-30 17:48 UTC, merged